Swagger Object:
  name: Swagger definition
  description: |
    This is the *root* document object for the API specification.
    It combines what previously was the Resource Listing and API Declaration (version 1.2 and earlier) together into one document.
  allowExtension: true
  swaggerType: true
  swaggerTypeURL: http://swagger.io/specification/#swaggerObject
  fields:
    - name: swagger
      type: string
      required: true
      description: |
        Specifies the Swagger Specification version being used.
        It can be used by the Swagger UI and other clients to interpret the API listing.
      values:
        - 2.0
    - name: info
      type: Info Object
      required: true
      description: |
        Provides metadata about the API.
        The metadata can be used by the clients if needed.
    - name : host
      type: string
      description: |
        The host (name or ip) serving the API.
        This MUST be the host only and does not include the scheme nor sub-paths.
        It MAY include a port.
        If the host is not included, the host serving the documentation is to be used (including the port).
        The host does not support path templating.
    - name: basePath
      type: string
      required: false
      description: |
        The base path on which the API is served, which is relative to the host.
        If it is not included, the API is served directly under the host.
        The value MUST start with a leading slash (/).
        The basePath does not support path templating.
    - name: schemes
      type: [string]
      description: |
        The transfer protocol of the API.
        If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself.
      values:
        - http
        - https
        - ws
        - wss
    - name: consumes
      type: [string]
      description": |
        A list of MIME types the APIs can consume.
        This is global to all APIs but can be overridden on specific API calls.
        Value MUST be as described under Mime Types.
    - name: produces
      type: [string]
      description: |
        A list of MIME types the APIs can produce.
        This is global to all APIs but can be overridden on specific API calls.
        Value MUST be as described under Mime Types.
    - name: paths
      type: Paths Object
      required: true
      description: The available paths and operations for the API.
    - name: definitions
      type: Definitions Object
      description: An object to hold data types produced and consumed by operations.
    - name: parameters
      type: Parameters Definitions Object
      description: |
        An object to hold parameters that can be used across operations.
        This property does not define global parameters for all operations.
    - name: responses
      type: Responses Definitions Object
      description: |
        An object to hold responses that can be used across operations.
        This property does not define global responses for all operations.
    - name: securityDefinitions
      type: Security Definitions Object
      description: Security scheme definitions that can be used across the specification.
    - name: security
      type: [Security Requirement Object]
      description: A declaration of which security schemes are applied for the API as a whole. The list of values describes alternative security schemes that can be used (that is, there is a logical OR between the security requirements). Individual operations can override this definition.
    - name: tags
      type: [Tag Object]
      description: A list of tags used by the specification with additional metadata. The order of the tags can be used to reflect on their order by the parsing tools. Not all tags that are used by the Operation Object must be declared. The tags that are not declared may be organized randomly or based on the tools' logic. Each tag name in the list MUST be unique.
    - name: externalDocs
      type: External Documentation Object
      description: Additional external documentation.
